; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    knolleary/PubSubClient
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson@^6.19.4
    paulstoffregen/OneWire
    milesburton/DallasTemperature
upload_protocol = espota        ;Comentar para programación SERIAL
;upload_port = COM3             ;Comentar para programación OTA
upload_port = Control_Patio     ;Comentar para programación SERIAL (Control_Patio)
upload_flags =                  ;Comentar para programación SERIAL
    --auth=EspAveni5            ;Comentar para programación SERIAL

build_flags =
    -DMQTT_MAX_PACKET_SIZE=1024

